export const API = {

  AUTH_LOGIN: '/auth/login',
  AUTH_REGISTER: '/auth/register',
  AUTH_PROFILE: '/auth/profile',
  AUTH_FORGOT_PASSWORD: '/auth/forgot-password',
  AUTH_RESET_PASSWORD: '/auth/reset-password',

  GEOCODE_RESOLVE: '/geocode/resolve',

  PROPERTIES: '/properties',
  PROPERTY_SUGGEST: '/properties/suggest',
  PROPERTY_DETAIL: (id: number | string) => `/properties/${id}`,
  PROPERTY_IMAGES_ARCHIVE: (id: number | string) => `/properties/${id}/images-archive`,
  PROPERTY_REVIEWS: (id: number | string) => `/properties/${id}/reviews`,
  PROPERTY_LISTING_OWNER: (id: number | string) => `/properties/${id}/listing-owner`,

  BOOKINGS: '/user/bookings',
  BOOKING_DETAIL: (id: number | string) => `/user/bookings/${id}`,
  WISHLIST: '/user/wishlist',
  WISHLIST_ITEM: (propertyId: number | string) => `/user/wishlist/${propertyId}`,
  USER_CONTACTS: '/user/contacts',
  USER_HISTORY: '/user/history',
  USER_HISTORY_ITEM: (propertyId: number | string) => `/user/history/${propertyId}`,

  REVIEWS: '/reviews',
  REVIEW_BY_TOKEN: (token: string) => `/reviews/token/${token}`,
  REVIEW_REPLY: (id: number | string) => `/reviews/${id}/reply`,
  PROPERTY_CREATE_REVIEW: (propertyId: number | string) => `/properties/${propertyId}/reviews`,

  AGENT_DASHBOARD: '/agent/dashboard',
  AGENT_PROPERTIES: '/agent/properties',
  AGENT_PROPERTY_DETAIL: (id: number | string) => `/agent/properties/${id}`,
  AGENT_PROPERTY_STATUS: (id: number | string) => `/agent/properties/${id}/status`,
  AGENT_CONTACTS: '/agent/contacts',
  AGENT_CONTACT_NOTE: (id: number | string) => `/agent/contacts/${id}/note`,
  AGENT_CONTACT_WORK_STATUS: (id: number | string) => `/agent/contacts/${id}/work-status`,
  AGENT_INQUIRIES: '/agent/inquiries',
  AGENT_INQUIRY_STATUS: (id: number | string) => `/agent/inquiries/${id}/status`,
  AGENT_REVIEW_LINK: (propertyId: number | string) => `/agent/review-link/${propertyId}`,

  ADMIN_DASHBOARD: '/admin/dashboard',
  ADMIN_AGENTS: '/admin/agents',
  ADMIN_AGENT_DETAIL: (id: number | string) => `/admin/agents/${id}`,
  ADMIN_AGENT_ROLE: (id: number | string) => `/admin/agents/${id}/role`,
  ADMIN_USERS: '/admin/users',
  ADMIN_USER_DETAIL: (id: number | string) => `/admin/users/${id}`,
  ADMIN_USER_RESET_PASSWORD: (id: number | string) => `/admin/users/${id}/reset-password`,
  ADMIN_PENDING_USERS: '/admin/users/pending',
  ADMIN_USER_APPROVE: (id: number | string) => `/admin/users/${id}/approve`,
  ADMIN_USER_REJECT: (id: number | string) => `/admin/users/${id}/reject`,
  ADMIN_BOOKINGS: '/admin/bookings',
  ADMIN_REASSIGN: (bookingId: number | string) => `/admin/bookings/${bookingId}/reassign`,
  ADMIN_PROPERTIES: '/admin/properties',
  ADMIN_FINANCIAL: '/admin/financial',
  ADMIN_FINANCIAL_EXPORT: '/admin/financial/export',
  ADMIN_AUDIT_LOGS: '/admin/audit-logs',
} as const
