export const DISTRICT_I18N: Record<string, { en: string; zh: string }> = {
  'พระนคร': { en: 'Phra Nakhon', zh: '拍那空' },
  'ดุสิต': { en: 'Dusit', zh: '律实' },
  'หนองจอก': { en: 'Nong Chok', zh: '侬促' },
  'บางรัก': { en: 'Bang Rak', zh: '挽乐' },
  'บางเขน': { en: 'Bang Khen', zh: '挽坚' },
  'บางกะปิ': { en: 'Bang Kapi', zh: '挽卡比' },
  'ปทุมวัน': { en: 'Pathum Wan', zh: '巴吞万' },
  'ป้อมปราบศัตรูพ่าย': { en: 'Pom Prap Sattruphai', zh: '蓬巴拉沙楚拍' },
  'พระโขนง': { en: 'Phra Khanong', zh: '拍昆仑' },
  'มีนบุรี': { en: 'Min Buri', zh: '民武里' },
  'ลาดกระบัง': { en: 'Lat Krabang', zh: '叻卡邦' },
  'ยานนาวา': { en: 'Yannawa', zh: '岩那瓦' },
  'สัมพันธวงศ์': { en: 'Samphanthawong', zh: '三潘他旺' },
  'พญาไท': { en: 'Phaya Thai', zh: '披耶泰' },
  'ธนบุรี': { en: 'Thon Buri', zh: '吞武里' },
  'บางกอกใหญ่': { en: 'Bangkok Yai', zh: '曼谷艾' },
  'ห้วยขวาง': { en: 'Huai Khwang', zh: '会广' },
  'คลองสาน': { en: 'Khlong San', zh: '空讪' },
  'ตลิ่งชัน': { en: 'Taling Chan', zh: '塔灵占' },
  'บางกอกน้อย': { en: 'Bangkok Noi', zh: '曼谷莲' },
  'บางขุนเทียน': { en: 'Bang Khun Thian', zh: '挽昆天' },
  'ภาษีเจริญ': { en: 'Phasi Charoen', zh: '帕世乍能' },
  'หนองแขม': { en: 'Nong Khaem', zh: '侬坎' },
  'ราษฎร์บูรณะ': { en: 'Rat Burana', zh: '叻布拉那' },
  'บางพลัด': { en: 'Bang Phlat', zh: '挽帕拉' },
  'ดินแดง': { en: 'Din Daeng', zh: '丁铃' },
  'บึงกุ่ม': { en: 'Bueng Kum', zh: '汶甘' },
  'สาทร': { en: 'Sathon', zh: '沙吞' },
  'บางซื่อ': { en: 'Bang Sue', zh: '挽赐' },
  'จตุจักร': { en: 'Chatuchak', zh: '乍都节' },
  'บางคอแหลม': { en: 'Bang Kho Laem', zh: '挽阔廉' },
  'ประเวศ': { en: 'Prawet', zh: '巴威' },
  'คลองเตย': { en: 'Khlong Toei', zh: '空堆' },
  'สวนหลวง': { en: 'Suan Luang', zh: '素安銮' },
  'จอมทอง': { en: 'Chom Thong', zh: '仲通' },
  'ดอนเมือง': { en: 'Don Mueang', zh: '敦孟' },
  'ราชเทวี': { en: 'Ratchathewi', zh: '拉差贴威' },
  'ลาดพร้าว': { en: 'Lat Phrao', zh: '叻抛' },
  'วัฒนา': { en: 'Watthana', zh: '哇他那' },
  'บางแค': { en: 'Bang Khae', zh: '挽坑' },
  'หลักสี่': { en: 'Lak Si', zh: '叻是' },
  'สายไหม': { en: 'Sai Mai', zh: '赛迈' },
  'คันนายาว': { en: 'Khanna Yao', zh: '坎那尧' },
  'สะพานสูง': { en: 'Saphan Sung', zh: '沙潘颂' },
  'วังทองหลาง': { en: 'Wang Thong Lang', zh: '旺通朗' },
  'คลองสามวา': { en: 'Khlong Sam Wa', zh: '空三瓦' },
  'บางนา': { en: 'Bang Na', zh: '挽那' },
  'ทวีวัฒนา': { en: 'Thawi Watthana', zh: '他威哇他那' },
  'ทุ่งครุ': { en: 'Thung Khru', zh: '通古' },
  'บางบอน': { en: 'Bang Bon', zh: '挽邦' },
  'เมืองกระบี่': { en: 'Mueang Krabi', zh: '甲米' },
  'เขาพนม': { en: 'Khao Phanom', zh: '考帕侬' },
  'เกาะลันตา': { en: 'Ko Lanta', zh: '高兰塔' },
  'คลองท่อม': { en: 'Khlong Thom', zh: '空通' },
  'อ่าวลึก': { en: 'Ao Luek', zh: '奥勒' },
  'ปลายพระยา': { en: 'Plai Phraya', zh: '巴莱披耶' },
  'ลำทับ': { en: 'Lam Thap', zh: '蓝塔' },
  'เหนือคลอง': { en: 'Nuea Khlong', zh: '嫩空' },
  'เมืองกาญจนบุรี': { en: 'Mueang Kanchanaburi', zh: '北碧' },
  'ไทรโยค': { en: 'Sai Yok', zh: '赛育' },
  'บ่อพลอย': { en: 'Bo Phloi', zh: '波普莱' },
  'ศรีสวัสดิ์': { en: 'Si Sawat', zh: '是沙瓦' },
  'ท่ามะกา': { en: 'Tha Maka', zh: '塔玛卡' },
  'ท่าม่วง': { en: 'Tha Muang', zh: '塔蒙' },
  'ทองผาภูมิ': { en: 'Thong Pha Phum', zh: '通帕蓬' },
  'สังขละบุรี': { en: 'Sangkhla Buri', zh: '桑卡拉武里' },
  'พนมทวน': { en: 'Phanom Thuan', zh: '帕侬端' },
  'เลาขวัญ': { en: 'Lao Khwan', zh: '劳宽' },
  'ด่านมะขามเตี้ย': { en: 'Dan Makham Tia', zh: '丹玛卡姆甸' },
  'หนองปรือ': { en: 'Nong Prue', zh: '侬普' },
  'ห้วยกระเจา': { en: 'Huai Krachao', zh: '会格拉朝' },
  'เมืองกาฬสินธุ์': { en: 'Mueang Kalasin', zh: '加拉信' },
  'นามน': { en: 'Na Mon', zh: '那蒙' },
  'กมลาไสย': { en: 'Kamalasai', zh: '卡玛拉塞' },
  'ร่องคำ': { en: 'Rong Kham', zh: '隆甘' },
  'กุฉินารายณ์': { en: 'Kuchinarai', zh: '固奇那莱' },
  'เขาวง': { en: 'Khao Wong', zh: '考旺' },
  'ยางตลาด': { en: 'Yang Talat', zh: '洋哒叻' },
  'ห้วยเม็ก': { en: 'Huai Mek', zh: '会梅' },
  'สหัสขันธ์': { en: 'Sahatsakhan', zh: '沙哈沙堪' },
  'คำม่วง': { en: 'Kham Muang', zh: '甘蒙' },
  'ท่าคันโท': { en: 'Tha Khantho', zh: '塔坎陀' },
  'หนองกุงศรี': { en: 'Nong Kung Si', zh: '侬昆是' },
  'สมเด็จ': { en: 'Somdet', zh: '颂德' },
  'ห้วยผึ้ง': { en: 'Huai Phueng', zh: '会蓬' },
  'สามชัย': { en: 'Sam Chai', zh: '三猜' },
  'นาคู': { en: 'Na Khu', zh: '那库' },
  'ดอนจาน': { en: 'Don Chan', zh: '敦占' },
  'ฆ้องชัย': { en: 'Khong Chai', zh: '孔猜' },
  'เมืองกำแพงเพชร': { en: 'Mueang Kamphaeng Phet', zh: '甘烹碧' },
  'ไทรงาม': { en: 'Sai Ngam', zh: '赛雅姆' },
  'คลองลาน': { en: 'Khlong Lan', zh: '空兰' },
  'ขาณุวรลักษบุรี': { en: 'Khanu Woralaksaburi', zh: '卡努沃拉叻沙武里' },
  'คลองขลุง': { en: 'Khlong Khlung', zh: '空孔' },
  'พรานกระต่าย': { en: 'Phran Kratai', zh: '潘格拉泰' },
  'ลานกระบือ': { en: 'Lan Krabue', zh: '兰格拉波' },
  'ทรายทองวัฒนา': { en: 'Sai Thong Watthana', zh: '赛通哇他那' },
  'ปางศิลาทอง': { en: 'Pang Sila Thong', zh: '庞是拉通' },
  'บึงสามัคคี': { en: 'Bueng Samakkhi', zh: '汶沙玛奇' },
  'โกสัมพีนคร': { en: 'Kosamphi Nakhon', zh: '哥三比那空' },
  'เมืองขอนแก่น': { en: 'Mueang Khon Kaen', zh: '孔敬' },
  'บ้านฝาง': { en: 'Ban Fang', zh: '班方' },
  'พระยืน': { en: 'Phra Yuen', zh: '拍元' },
  'หนองเรือ': { en: 'Nong Ruea', zh: '侬勒阿' },
  'ชุมแพ': { en: 'Chum Phae', zh: '春佩' },
  'สีชมพู': { en: 'Si Chomphu', zh: '是仲蒲' },
  'น้ำพอง': { en: 'Nam Phong', zh: '南蓬' },
  'อุบลรัตน์': { en: 'Ubolratana', zh: '乌汶叻他那' },
  'กระนวน': { en: 'Kranuan', zh: '格拉端' },
  'บ้านไผ่': { en: 'Ban Phai', zh: '班派' },
  'เปือยน้อย': { en: 'Pueai Noi', zh: '普埃莲' },
  'พล': { en: 'Phon', zh: '蓬' },
  'แวงใหญ่': { en: 'Waeng Yai', zh: '万艾' },
  'แวงน้อย': { en: 'Waeng Noi', zh: '万莲' },
  'หนองสองห้อง': { en: 'Nong Song Hong', zh: '侬松洪' },
  'ภูเวียง': { en: 'Phu Wiang', zh: '普威昂' },
  'มัญจาคีรี': { en: 'Mancha Khiri', zh: '曼差基里' },
  'ชนบท': { en: 'Chonnabot', zh: '春那博' },
  'เขาสวนกวาง': { en: 'Khao Suan Kwang', zh: '考素安广' },
  'ภูผาม่าน': { en: 'Phu Phaman', zh: '普帕曼' },
  'ซำสูง': { en: 'Sam Sung', zh: '三颂' },
  'โคกโพธิ์ไชย': { en: 'Khok Pho Chai', zh: '廓菩猜' },
  'หนองนาคำ': { en: 'Nong Na Kham', zh: '侬那甘' },
  'บ้านแฮด': { en: 'Ban Haet', zh: '班号' },
  'โนนศิลา': { en: 'Non Sila', zh: '侬是拉' },
  'เวียงเก่า': { en: 'Wiang Kao', zh: '威昂考' },
  'เมืองจันทบุรี': { en: 'Mueang Chanthaburi', zh: '尖竹汶' },
  'ขลุง': { en: 'Khlung', zh: '孔' },
  'ท่าใหม่': { en: 'Tha Mai', zh: '塔迈' },
  'โป่งน้ำร้อน': { en: 'Pong Nam Ron', zh: '蓬南隆' },
  'มะขาม': { en: 'Makham', zh: '玛卡姆' },
  'แหลมสิงห์': { en: 'Laem Sing', zh: '廉信' },
  'สอยดาว': { en: 'Soi Dao', zh: '索道' },
  'แก่งหางแมว': { en: 'Kaeng Hang Maeo', zh: '坑昂苗' },
  'นายายอาม': { en: 'Na Yai Am', zh: '那艾安' },
  'เขาคิชฌกูฏ': { en: 'Khao Khitchakut', zh: '考吉乍固' },
  'เมืองฉะเชิงเทรา': { en: 'Mueang Chachoengsao', zh: '北柳' },
  'บางคล้า': { en: 'Bang Khla', zh: '挽克拉' },
  'บางน้ำเปรี้ยว': { en: 'Bang Nam Priao', zh: '挽南巴廖' },
  'บางปะกง': { en: 'Bang Pakong', zh: '挽巴公' },
  'บ้านโพธิ์': { en: 'Ban Pho', zh: '班菩' },
  'พนมสารคาม': { en: 'Phanom Sarakham', zh: '帕侬沙拉堪' },
  'ราชสาส์น': { en: 'Ratchasan', zh: '拉差讪' },
  'สนามชัยเขต': { en: 'Sanam Chai Khet', zh: '沙南猜吉' },
  'แปลงยาว': { en: 'Plaeng Yao', zh: '编尧' },
  'ท่าตะเกียบ': { en: 'Tha Takiap', zh: '塔塔甲' },
  'คลองเขื่อน': { en: 'Khlong Khuean', zh: '空昆' },
  'เมืองชลบุรี': { en: 'Mueang Chon Buri', zh: '春武里' },
  'บ้านบึง': { en: 'Ban Bueng', zh: '班汶' },
  'หนองใหญ่': { en: 'Nong Yai', zh: '侬艾' },
  'บางละมุง': { en: 'Bang Lamung', zh: '挽拉蒙' },
  'พานทอง': { en: 'Phan Thong', zh: '潘通' },
  'พนัสนิคม': { en: 'Phanat Nikhom', zh: '帕纳尼空' },
  'ศรีราชา': { en: 'Si Racha', zh: '是拉差' },
  'เกาะสีชัง': { en: 'Ko Sichang', zh: '高是昌' },
  'สัตหีบ': { en: 'Sattahip', zh: '沙他希' },
  'บ่อทอง': { en: 'Bo Thong', zh: '波通' },
  'เกาะจันทร์': { en: 'Ko Chan', zh: '高占' },
  'เมืองชัยนาท': { en: 'Mueang Chai Nat', zh: '猜纳' },
  'มโนรมย์': { en: 'Manorom', zh: '玛诺隆' },
  'วัดสิงห์': { en: 'Wat Sing', zh: '越信' },
  'สรรพยา': { en: 'Sapphaya', zh: '萨帕耶' },
  'สรรคบุรี': { en: 'Sankhaburi', zh: '桑卡武里' },
  'หันคา': { en: 'Hankha', zh: '汉卡' },
  'หนองมะโมง': { en: 'Nong Mamong', zh: '侬玛蒙' },
  'เนินขาม': { en: 'Noen Kham', zh: '嫩甘' },
  'เมืองชัยภูมิ': { en: 'Mueang Chaiyaphum', zh: '猜也蓬' },
  'บ้านเขว้า': { en: 'Ban Khwao', zh: '班快' },
  'คอนสวรรค์': { en: 'Khon Sawan', zh: '孔沙旺' },
  'เกษตรสมบูรณ์': { en: 'Kaset Sombun', zh: '卡实颂汶' },
  'หนองบัวแดง': { en: 'Nong Bua Daeng', zh: '侬蒲铃' },
  'จัตุรัส': { en: 'Chatturat', zh: '乍杜叻' },
  'บำเหน็จณรงค์': { en: 'Bamnet Narong', zh: '邦尼那隆' },
  'หนองบัวระเหว': { en: 'Nong Bua Rawe', zh: '侬蒲拉威' },
  'เทพสถิต': { en: 'Thep Sathit', zh: '贴沙提' },
  'ภูเขียว': { en: 'Phu Khiao', zh: '普乔' },
  'บ้านแท่น': { en: 'Ban Thaen', zh: '班探' },
  'แก้งคร้อ': { en: 'Kaeng Khro', zh: '坑克罗' },
  'คอนสาร': { en: 'Khon San', zh: '孔讪' },
  'ภักดีชุมพล': { en: 'Phakdi Chumphon', zh: '帕迪春蓬' },
  'เนินสง่า': { en: 'Noen Sa-Nga', zh: '嫩沙雅' },
  'ซับใหญ่': { en: 'Sap Yai', zh: '萨艾' },
  'เมืองชุมพร': { en: 'Mueang Chumphon', zh: '春蓬' },
  'ท่าแซะ': { en: 'Tha Sae', zh: '塔塞' },
  'ปะทิว': { en: 'Pathio', zh: '巴帖' },
  'หลังสวน': { en: 'Lang Suan', zh: '朗素安' },
  'ละแม': { en: 'Lamae', zh: '拉湄' },
  'พะโต๊ะ': { en: 'Phato', zh: '帕托' },
  'สวี': { en: 'Sawi', zh: '沙威' },
  'ทุ่งตะโก': { en: 'Thung Tako', zh: '通塔高' },
  'เมืองเชียงราย': { en: 'Mueang Chiang Rai', zh: '清莱' },
  'เวียงชัย': { en: 'Wiang Chai', zh: '威昂猜' },
  'เชียงของ': { en: 'Chiang Khong', zh: '清孔' },
  'เทิง': { en: 'Thoeng', zh: '通' },
  'พาน': { en: 'Phan', zh: '潘' },
  'ป่าแดด': { en: 'Pa Daet', zh: '巴德' },
  'แม่จัน': { en: 'Mae Chan', zh: '湄占' },
  'เชียงแสน': { en: 'Chiang Saen', zh: '清森' },
  'แม่สาย': { en: 'Mae Sai', zh: '湄赛' },
  'แม่สรวย': { en: 'Mae Suai', zh: '湄素埃' },
  'เวียงป่าเป้า': { en: 'Wiang Pa Pao', zh: '威昂巴包' },
  'พญาเม็งราย': { en: 'Phaya Mengrai', zh: '披耶孟莱' },
  'เวียงแก่น': { en: 'Wiang Kaen', zh: '威昂坚' },
  'ขุนตาล': { en: 'Khun Tan', zh: '昆丹' },
  'แม่ฟ้าหลวง': { en: 'Mae Fa Luang', zh: '湄法銮' },
  'แม่ลาว': { en: 'Mae Lao', zh: '湄劳' },
  'เวียงเชียงรุ้ง': { en: 'Wiang Chiang Rung', zh: '威昂清隆' },
  'ดอยหลวง': { en: 'Doi Luang', zh: '岛銮' },
  'เมืองเชียงใหม่': { en: 'Mueang Chiang Mai', zh: '清迈' },
  'แม่แจ่ม': { en: 'Mae Chaem', zh: '湄参' },
  'เชียงดาว': { en: 'Chiang Dao', zh: '清道' },
  'ดอยสะเก็ด': { en: 'Doi Saket', zh: '岛沙吉' },
  'แม่แตง': { en: 'Mae Taeng', zh: '湄登' },
  'แม่ริม': { en: 'Mae Rim', zh: '湄林' },
  'สะเมิง': { en: 'Samoeng', zh: '沙梅' },
  'ฝาง': { en: 'Fang', zh: '方' },
  'แม่อาย': { en: 'Mae Ai', zh: '湄艾' },
  'พร้าว': { en: 'Phrao', zh: '抛' },
  'สันป่าตอง': { en: 'San Pa Tong', zh: '讪巴通' },
  'สันกำแพง': { en: 'San Kamphaeng', zh: '讪甘烹' },
  'สันทราย': { en: 'San Sai', zh: '讪赛' },
  'หางดง': { en: 'Hang Dong', zh: '昂东' },
  'ฮอด': { en: 'Hot', zh: '何' },
  'ดอยเต่า': { en: 'Doi Tao', zh: '岛岛' },
  'อมก๋อย': { en: 'Omkoi', zh: '翁刁' },
  'สารภี': { en: 'Saraphi', zh: '沙拉披' },
  'เวียงแหง': { en: 'Wiang Haeng', zh: '威昂亨' },
  'ไชยปราการ': { en: 'Chai Prakan', zh: '猜巴甘' },
  'แม่วาง': { en: 'Mae Wang', zh: '湄旺' },
  'แม่ออน': { en: 'Mae On', zh: '湄安' },
  'ดอยหล่อ': { en: 'Doi Lo', zh: '岛罗' },
  'กัลยาณิวัฒนา': { en: 'Kanlayaniwatthana', zh: '甘拉亚尼哇他那' },
  'เมืองตรัง': { en: 'Mueang Trang', zh: '董里' },
  'กันตัง': { en: 'Kantang', zh: '甘当' },
  'ย่านตาขาว': { en: 'Yan Ta Khao', zh: '岩塔考' },
  'ปะเหลียน': { en: 'Palian', zh: '巴联' },
  'สิเกา': { en: 'Sikao', zh: '是考' },
  'ห้วยยอด': { en: 'Huai Yot', zh: '会育' },
  'วังวิเศษ': { en: 'Wang Wiset', zh: '旺威实' },
  'นาโยง': { en: 'Na Yong', zh: '那荣' },
  'รัษฎา': { en: 'Ratsada', zh: '叻沙达' },
  'หาดสำราญ': { en: 'Hat Samran', zh: '哈沙兰' },
  'เมืองตราด': { en: 'Mueang Trat', zh: '达叻' },
  'คลองใหญ่': { en: 'Khlong Yai', zh: '空艾' },
  'เขาสมิง': { en: 'Khao Saming', zh: '考沙明' },
  'บ่อไร่': { en: 'Bo Rai', zh: '波莱' },
  'แหลมงอบ': { en: 'Laem Ngop', zh: '廉阿' },
  'เกาะกูด': { en: 'Ko Kut', zh: '高固' },
  'เกาะช้าง': { en: 'Ko Chang', zh: '高昌' },
  'เมืองตาก': { en: 'Mueang Tak', zh: '来兴' },
  'บ้านตาก': { en: 'Ban Tak', zh: '班达' },
  'สามเงา': { en: 'Sam Ngao', zh: '三敖' },
  'แม่ระมาด': { en: 'Mae Ramat', zh: '湄拉玛' },
  'ท่าสองยาง': { en: 'Tha Song Yang', zh: '塔松洋' },
  'แม่สอด': { en: 'Mae Sot', zh: '湄索' },
  'พบพระ': { en: 'Phop Phra', zh: '蒲拍' },
  'อุ้มผาง': { en: 'Um Phang', zh: '乌姆庞' },
  'วังเจ้า': { en: 'Wang Chao', zh: '旺昭' },
  'เมืองนครนายก': { en: 'Mueang Nakhon Nayok', zh: '那空那育' },
  'ปากพลี': { en: 'Pak Phli', zh: '北普里' },
  'บ้านนา': { en: 'Ban Na', zh: '班那' },
  'องครักษ์': { en: 'Ongkharak', zh: '翁卡拉' },
  'เมืองนครปฐม': { en: 'Mueang Nakhon Pathom', zh: '佛统' },
  'กำแพงแสน': { en: 'Kamphaeng Saen', zh: '甘烹森' },
  'นครชัยศรี': { en: 'Nakhon Chai Si', zh: '那空猜是' },
  'ดอนตูม': { en: 'Don Tum', zh: '敦吞' },
  'บางเลน': { en: 'Bang Len', zh: '挽连' },
  'สามพราน': { en: 'Sam Phran', zh: '三潘' },
  'พุทธมณฑล': { en: 'Phutthamonthon', zh: '普他蒙吞' },
  'เมืองนครพนม': { en: 'Mueang Nakhon Phanom', zh: '那空拍侬' },
  'ปลาปาก': { en: 'Pla Pak', zh: '巴拉北' },
  'ท่าอุเทน': { en: 'Tha Uthen', zh: '塔乌坍' },
  'บ้านแพง': { en: 'Ban Phaeng', zh: '班佩' },
  'ธาตุพนม': { en: 'That Phanom', zh: '塔帕侬' },
  'เรณูนคร': { en: 'Renu Nakhon', zh: '勒努那空' },
  'นาแก': { en: 'Na Kae', zh: '那皆' },
  'ศรีสงคราม': { en: 'Si Songkhram', zh: '是颂堪' },
  'นาหว้า': { en: 'Na Wa', zh: '那瓦' },
  'โพนสวรรค์': { en: 'Phon Sawan', zh: '蓬沙旺' },
  'นาทม': { en: 'Na Thom', zh: '那通' },
  'วังยาง': { en: 'Wang Yang', zh: '旺洋' },
  'เมืองนครราชสีมา': { en: 'Mueang Nakhon Ratchasima', zh: '呵叻' },
  'ครบุรี': { en: 'Khon Buri', zh: '孔武里' },
  'เสิงสาง': { en: 'Soeng Sang', zh: '森桑' },
  'คง': { en: 'Khong', zh: '孔' },
  'บ้านเหลื่อม': { en: 'Ban Lueam', zh: '班廉' },
  'จักราช': { en: 'Chakkarat', zh: '乍卡叻' },
  'โชคชัย': { en: 'Chok Chai', zh: '促猜' },
  'ด่านขุนทด': { en: 'Dan Khun Thot', zh: '丹昆陀' },
  'โนนไทย': { en: 'Non Thai', zh: '侬泰' },
  'โนนสูง': { en: 'Non Sung', zh: '侬颂' },
  'ขามสะแกแสง': { en: 'Kham Sakaesaeng', zh: '甘沙皆森' },
  'บัวใหญ่': { en: 'Bua Yai', zh: '蒲艾' },
  'ประทาย': { en: 'Prathai', zh: '巴泰' },
  'ปักธงชัย': { en: 'Pak Thong Chai', zh: '北通猜' },
  'พิมาย': { en: 'Phimai', zh: '披迈' },
  'ห้วยแถลง': { en: 'Huai Thalaeng', zh: '会他冷' },
  'ชุมพวง': { en: 'Chum Phuang', zh: '春普昂' },
  'สูงเนิน': { en: 'Sung Noen', zh: '颂嫩' },
  'ขามทะเลสอ': { en: 'Kham Thale So', zh: '甘塔莱索' },
  'สีคิ้ว': { en: 'Si Khio', zh: '是乔' },
  'ปากช่อง': { en: 'Pak Chong', zh: '北冲' },
  'หนองบุญมาก': { en: 'Nong Bunmak', zh: '侬汶玛' },
  'แก้งสนามนาง': { en: 'Kaeng Sanam Nang', zh: '坑沙南南' },
  'โนนแดง': { en: 'Non Daeng', zh: '侬铃' },
  'วังน้ำเขียว': { en: 'Wang Nam Khiao', zh: '旺南乔' },
  'เทพารักษ์': { en: 'Thepharak', zh: '贴帕拉' },
  'เมืองยาง': { en: 'Mueang Yang', zh: '孟洋' },
  'พระทองคำ': { en: 'Phra Thong Kham', zh: '拍通甘' },
  'ลำทะเมนชัย': { en: 'Lam Thamenchai', zh: '蓝塔面猜' },
  'บัวลาย': { en: 'Bua Lai', zh: '蒲莱' },
  'สีดา': { en: 'Sida', zh: '是达' },
  'เฉลิมพระเกียรติ': { en: 'Chaloem Phra Kiat', zh: '崇拍吉' },
  'เมืองนครศรีธรรมราช': { en: 'Mueang Nakhon Si Thammarat', zh: '洛坤' },
  'พรหมคีรี': { en: 'Phrom Khiri', zh: '拍隆基里' },
  'ลานสกา': { en: 'Lan Saka', zh: '兰沙卡' },
  'ฉวาง': { en: 'Chawang', zh: '差旺' },
  'พิปูน': { en: 'Phipun', zh: '披蓬' },
  'เชียรใหญ่': { en: 'Chian Yai', zh: '建艾' },
  'ชะอวด': { en: 'Cha-Uat', zh: '差哇' },
  'ท่าศาลา': { en: 'Tha Sala', zh: '塔沙拉' },
  'ทุ่งสง': { en: 'Thung Song', zh: '通松' },
  'นาบอน': { en: 'Na Bon', zh: '那邦' },
  'ทุ่งใหญ่': { en: 'Thung Yai', zh: '通艾' },
  'ปากพนัง': { en: 'Pak Phanang', zh: '北帕南' },
  'ร่อนพิบูลย์': { en: 'Ron Phibun', zh: '隆披汶' },
  'สิชล': { en: 'Sichon', zh: '是春' },
  'ขนอม': { en: 'Khanom', zh: '卡农' },
  'หัวไทร': { en: 'Hua Sai', zh: '华赛' },
  'บางขัน': { en: 'Bang Khan', zh: '挽坎' },
  'ถ้ำพรรณรา': { en: 'Tham Phannara', zh: '探潘那拉' },
  'จุฬาภรณ์': { en: 'Chulabhorn', zh: '朱拉蓬' },
  'พระพรหม': { en: 'Phra Phrom', zh: '拍拍隆' },
  'นบพิตำ': { en: 'Nopphitam', zh: '诺披坦' },
  'ช้างกลาง': { en: 'Chang Klang', zh: '昌格朗' },
  'เมืองนครสวรรค์': { en: 'Mueang Nakhon Sawan', zh: '北榄坡' },
  'โกรกพระ': { en: 'Krok Phra', zh: '克罗拍' },
  'ชุมแสง': { en: 'Chum Saeng', zh: '春盛' },
  'หนองบัว': { en: 'Nong Bua', zh: '侬蒲' },
  'บรรพตพิสัย': { en: 'Banphot Phisai', zh: '班蓬披赛' },
  'เก้าเลี้ยว': { en: 'Kao Liao', zh: '考廖' },
  'ตาคลี': { en: 'Takhli', zh: '达克里' },
  'ท่าตะโก': { en: 'Tha Tako', zh: '塔塔高' },
  'ไพศาลี': { en: 'Phaisali', zh: '派沙里' },
  'พยุหะคีรี': { en: 'Phayuha Khiri', zh: '帕育哈基里' },
  'ลาดยาว': { en: 'Lat Yao', zh: '叻尧' },
  'ตากฟ้า': { en: 'Tak Fa', zh: '达法' },
  'แม่วงก์': { en: 'Mae Wong', zh: '湄旺' },
  'แม่เปิน': { en: 'Mae Poen', zh: '湄编' },
  'ชุมตาบง': { en: 'Chum Ta Bong', zh: '春塔邦' },
  'เมืองนนทบุรี': { en: 'Mueang Nonthaburi', zh: '暖武里' },
  'บางกรวย': { en: 'Bang Kruai', zh: '挽快' },
  'บางใหญ่': { en: 'Bang Yai', zh: '挽艾' },
  'บางบัวทอง': { en: 'Bang Bua Thong', zh: '挽蒲通' },
  'ไทรน้อย': { en: 'Sai Noi', zh: '赛莲' },
  'ปากเกร็ด': { en: 'Pak Kret', zh: '北革' },
  'เมืองนราธิวาส': { en: 'Mueang Narathiwat', zh: '陶公' },
  'ตากใบ': { en: 'Tak Bai', zh: '达拜' },
  'บาเจาะ': { en: 'Bacho', zh: '巴昭' },
  'ยี่งอ': { en: 'Yi-Ngo', zh: '依阿' },
  'ระแงะ': { en: 'Ra-Ngae', zh: '拉艾' },
  'รือเสาะ': { en: 'Rueso', zh: '勒索' },
  'ศรีสาคร': { en: 'Si Sakhon', zh: '是沙孔' },
  'แว้ง': { en: 'Waeng', zh: '万' },
  'สุคิริน': { en: 'Sukhirin', zh: '素奇林' },
  'สุไหงโก-ลก': { en: 'Su-Ngai Kolok', zh: '素艾哥洛' },
  'สุไหงปาดี': { en: 'Su-Ngai Padi', zh: '素艾巴迪' },
  'จะแนะ': { en: 'Chanae', zh: '差奈' },
  'เจาะไอร้อง': { en: 'Cho-Airong', zh: '昭艾隆' },
  'เมืองน่าน': { en: 'Mueang Nan', zh: '楠府' },
  'แม่จริม': { en: 'Mae Charim', zh: '湄差林' },
  'บ้านหลวง': { en: 'Ban Luang', zh: '班銮' },
  'นาน้อย': { en: 'Na Noi', zh: '那莲' },
  'ปัว': { en: 'Pua', zh: '蒲阿' },
  'ท่าวังผา': { en: 'Tha Wang Pha', zh: '塔旺帕' },
  'เวียงสา': { en: 'Wiang Sa', zh: '威昂沙' },
  'ทุ่งช้าง': { en: 'Thung Chang', zh: '通昌' },
  'เชียงกลาง': { en: 'Chiang Klang', zh: '清格朗' },
  'นาหมื่น': { en: 'Na Muen', zh: '那满' },
  'สันติสุข': { en: 'Santi Suk', zh: '讪提素' },
  'บ่อเกลือ': { en: 'Bo Kluea', zh: '波格勒' },
  'สองแคว': { en: 'Song Khwae', zh: '松快' },
  'ภูเพียง': { en: 'Phu Phiang', zh: '普平' },
  'เมืองบึงกาฬ': { en: 'Mueang Bueng Kan', zh: '汶干' },
  'พรเจริญ': { en: 'Phon Charoen', zh: '蓬乍能' },
  'โซ่พิสัย': { en: 'So Phisai', zh: '索披赛' },
  'เซกา': { en: 'Seka', zh: '塞卡' },
  'ปากคาด': { en: 'Pak Khat', zh: '北卡' },
  'บึงโขงหลง': { en: 'Bueng Khong Long', zh: '汶孔龙' },
  'ศรีวิไล': { en: 'Si Wilai', zh: '是威莱' },
  'บุ่งคล้า': { en: 'Bung Khla', zh: '汶克拉' },
  'เมืองบุรีรัมย์': { en: 'Mueang Buri Ram', zh: '武里南' },
  'คูเมือง': { en: 'Khu Mueang', zh: '库孟' },
  'กระสัง': { en: 'Krasang', zh: '格拉桑' },
  'นางรอง': { en: 'Nang Rong', zh: '南隆' },
  'หนองกี่': { en: 'Nong Ki', zh: '侬基' },
  'ละหานทราย': { en: 'Lahan Sai', zh: '拉汉赛' },
  'ประโคนชัย': { en: 'Prakhon Chai', zh: '巴孔猜' },
  'บ้านกรวด': { en: 'Ban Kruat', zh: '班快' },
  'พุทไธสง': { en: 'Phutthaisong', zh: '普泰颂' },
  'ลำปลายมาศ': { en: 'Lam Plai Mat', zh: '蓝巴莱玛' },
  'สตึก': { en: 'Satuek', zh: '沙德' },
  'ปะคำ': { en: 'Pakham', zh: '巴甘' },
  'นาโพธิ์': { en: 'Na Pho', zh: '那菩' },
  'หนองหงส์': { en: 'Nong Hong', zh: '侬洪' },
  'พลับพลาชัย': { en: 'Phlapphla Chai', zh: '帕拉帕拉猜' },
  'ห้วยราช': { en: 'Huai Rat', zh: '会叻' },
  'โนนสุวรรณ': { en: 'Non Suwan', zh: '侬素万' },
  'ชำนิ': { en: 'Chamni', zh: '差尼' },
  'บ้านใหม่ไชยพจน์': { en: 'Ban Mai Chaiyaphot', zh: '班迈猜耶蓬' },
  'โนนดินแดง': { en: 'Non Din Daeng', zh: '侬丁铃' },
  'บ้านด่าน': { en: 'Ban Dan', zh: '班丹' },
  'แคนดง': { en: 'Khaen Dong', zh: '坚东' },
  'เมืองปทุมธานี': { en: 'Mueang Pathum Thani', zh: '巴吞他尼' },
  'คลองหลวง': { en: 'Khlong Luang', zh: '空銮' },
  'ธัญบุรี': { en: 'Thanyaburi', zh: '探雅武里' },
  'หนองเสือ': { en: 'Nong Suea', zh: '侬舍' },
  'ลาดหลุมแก้ว': { en: 'Lat Lum Kaeo', zh: '叻隆缴' },
  'ลำลูกกา': { en: 'Lam Luk Ka', zh: '蓝律卡' },
  'สามโคก': { en: 'Sam Khok', zh: '三廓' },
  'เมืองประจวบคีรีขันธ์': { en: 'Mueang Prachuap Khiri Khan', zh: '班武里' },
  'กุยบุรี': { en: 'Kui Buri', zh: '桂武里' },
  'ทับสะแก': { en: 'Thap Sakae', zh: '塔沙皆' },
  'บางสะพาน': { en: 'Bang Saphan', zh: '挽沙潘' },
  'บางสะพานน้อย': { en: 'Bang Saphan Noi', zh: '挽沙潘莲' },
  'ปราณบุรี': { en: 'Pran Buri', zh: '潘武里' },
  'หัวหิน': { en: 'Hua Hin', zh: '华欣' },
  'สามร้อยยอด': { en: 'Sam Roi Yot', zh: '三黎育' },
  'เมืองปราจีนบุรี': { en: 'Mueang Prachin Buri', zh: '巴真' },
  'กบินทร์บุรี': { en: 'Kabin Buri', zh: '甲民武里' },
  'นาดี': { en: 'Na Di', zh: '那迪' },
  'บ้านสร้าง': { en: 'Ban Sang', zh: '班桑' },
  'ประจันตคาม': { en: 'Prachantakham', zh: '巴占塔堪' },
  'ศรีมหาโพธิ': { en: 'Si Maha Phot', zh: '是玛哈蒲' },
  'ศรีมโหสถ': { en: 'Si Mahosot', zh: '是玛贺索' },
  'เมืองปัตตานี': { en: 'Mueang Pattani', zh: '北大年' },
  'โคกโพธิ์': { en: 'Khok Pho', zh: '廓菩' },
  'หนองจิก': { en: 'Nong Chik', zh: '侬集' },
  'ปะนาเระ': { en: 'Panare', zh: '巴那雷' },
  'มายอ': { en: 'Mayo', zh: '玛育' },
  'ทุ่งยางแดง': { en: 'Thung Yang Daeng', zh: '通洋铃' },
  'สายบุรี': { en: 'Sai Buri', zh: '赛武里' },
  'ไม้แก่น': { en: 'Mai Kaen', zh: '迈坚' },
  'ยะหริ่ง': { en: 'Yaring', zh: '亚令' },
  'ยะรัง': { en: 'Yarang', zh: '亚朗' },
  'กะพ้อ': { en: 'Kapho', zh: '甲坡' },
  'แม่ลาน': { en: 'Mae Lan', zh: '湄兰' },
  'พระนครศรีอยุธยา': { en: 'Phra Nakhon Si Ayutthaya', zh: '大城' },
  'ท่าเรือ': { en: 'Tha Ruea', zh: '塔勒阿' },
  'นครหลวง': { en: 'Nakhon Luang', zh: '那空銮' },
  'บางไทร': { en: 'Bang Sai', zh: '挽赛' },
  'บางบาล': { en: 'Bang Ban', zh: '挽班' },
  'บางปะอิน': { en: 'Bang Pa-In', zh: '挽巴因' },
  'บางปะหัน': { en: 'Bang Pahan', zh: '挽巴汉' },
  'ผักไห่': { en: 'Phak Hai', zh: '帕海' },
  'ภาชี': { en: 'Phachi', zh: '帕集' },
  'ลาดบัวหลวง': { en: 'Lat Bua Luang', zh: '叻蒲銮' },
  'วังน้อย': { en: 'Wang Noi', zh: '旺莲' },
  'เสนา': { en: 'Sena', zh: '社那' },
  'บางซ้าย': { en: 'Bang Sai', zh: '挽赛' },
  'อุทัย': { en: 'Uthai', zh: '乌泰' },
  'มหาราช': { en: 'Maha Rat', zh: '玛哈叻' },
  'บ้านแพรก': { en: 'Ban Phraek', zh: '班佩' },
  'เมืองพังงา': { en: 'Mueang Phang-Nga', zh: '攀牙' },
  'เกาะยาว': { en: 'Ko Yao', zh: '高尧' },
  'กะปง': { en: 'Kapong', zh: '卡邦' },
  'ตะกั่วทุ่ง': { en: 'Takua Thung', zh: '塔瓜通' },
  'ตะกั่วป่า': { en: 'Takua Pa', zh: '塔瓜巴' },
  'คุระบุรี': { en: 'Khura Buri', zh: '库拉武里' },
  'ทับปุด': { en: 'Thap Put', zh: '塔普' },
  'ท้ายเหมือง': { en: 'Thai Mueang', zh: '泰孟' },
  'เมืองพัทลุง': { en: 'Mueang Phatthalung', zh: '博他仑' },
  'กงหรา': { en: 'Kong Ra', zh: '公拉' },
  'เขาชัยสน': { en: 'Khao Chaison', zh: '考采颂' },
  'ตะโหมด': { en: 'Tamot', zh: '塔莫' },
  'ควนขนุน': { en: 'Khuan Khanun', zh: '昆卡侬' },
  'ปากพะยูน': { en: 'Pak Phayun', zh: '北帕允' },
  'ศรีบรรพต': { en: 'Si Banphot', zh: '是班蓬' },
  'ป่าบอน': { en: 'Pa Bon', zh: '巴邦' },
  'บางแก้ว': { en: 'Bang Kaeo', zh: '挽缴' },
  'ป่าพะยอม': { en: 'Pa Phayom', zh: '巴帕荣' },
  'ศรีนครินทร์': { en: 'Srinagarindra', zh: '诗纳卡琳' },
  'เมืองพิจิตร': { en: 'Mueang Phichit', zh: '披集' },
  'วังทรายพูน': { en: 'Wang Sai Phun', zh: '旺赛普' },
  'โพธิ์ประทับช้าง': { en: 'Pho Prathap Chang', zh: '菩巴他昌' },
  'ตะพานหิน': { en: 'Taphan Hin', zh: '塔潘欣' },
  'บางมูลนาก': { en: 'Bang Mun Nak', zh: '挽满那' },
  'โพทะเล': { en: 'Pho Thale', zh: '菩塔莱' },
  'สามง่าม': { en: 'Sam Ngam', zh: '三雅姆' },
  'ทับคล้อ': { en: 'Tap Khlo', zh: '塔克罗' },
  'สากเหล็ก': { en: 'Sak Lek', zh: '沙勒' },
  'บึงนาราง': { en: 'Bueng Na Rang', zh: '汶那朗' },
  'ดงเจริญ': { en: 'Dong Charoen', zh: '东乍能' },
  'วชิรบารมี': { en: 'Wachirabarami', zh: '哇集拉巴拉米' },
  'เมืองพิษณุโลก': { en: 'Mueang Phitsanulok', zh: '彭世洛' },
  'นครไทย': { en: 'Nakhon Thai', zh: '那空泰' },
  'ชาติตระการ': { en: 'Chat Trakan', zh: '差达堪' },
  'บางระกำ': { en: 'Bang Rakam', zh: '挽拉甘' },
  'บางกระทุ่ม': { en: 'Bang Krathum', zh: '挽格拉通' },
  'พรหมพิราม': { en: 'Phrom Phiram', zh: '拍隆披蓝' },
  'วัดโบสถ์': { en: 'Wat Bot', zh: '越博' },
  'วังทอง': { en: 'Wang Thong', zh: '旺通' },
  'เนินมะปราง': { en: 'Noen Maprang', zh: '嫩玛庞' },
  'เมืองเพชรบุรี': { en: 'Mueang Phetchaburi', zh: '碧武里' },
  'เขาย้อย': { en: 'Khao Yoi', zh: '考育' },
  'หนองหญ้าปล้อง': { en: 'Nong Ya Plong', zh: '侬亚蓬' },
  'ชะอำ': { en: 'Cha-Am', zh: '差安' },
  'ท่ายาง': { en: 'Tha Yang', zh: '塔洋' },
  'บ้านลาด': { en: 'Ban Lat', zh: '班叻' },
  'บ้านแหลม': { en: 'Ban Laem', zh: '班廉' },
  'แก่งกระจาน': { en: 'Kaeng Krachan', zh: '坑格拉参' },
  'เมืองเพชรบูรณ์': { en: 'Mueang Phetchabun', zh: '碧差汶' },
  'ชนแดน': { en: 'Chon Daen', zh: '春甸' },
  'หล่มสัก': { en: 'Lom Sak', zh: '隆沙' },
  'หล่มเก่า': { en: 'Lom Kao', zh: '隆考' },
  'วิเชียรบุรี': { en: 'Wichian Buri', zh: '威建武里' },
  'ศรีเทพ': { en: 'Si Thep', zh: '是贴' },
  'หนองไผ่': { en: 'Nong Phai', zh: '侬派' },
  'บึงสามพัน': { en: 'Bueng Sam Phan', zh: '汶三潘' },
  'น้ำหนาว': { en: 'Nam Nao', zh: '南脑' },
  'วังโป่ง': { en: 'Wang Pong', zh: '旺蓬' },
  'เขาค้อ': { en: 'Khao Kho', zh: '考阔' },
  'เมืองแพร่': { en: 'Mueang Phrae', zh: '帕府' },
  'ร้องกวาง': { en: 'Rong Kwang', zh: '隆广' },
  'ลอง': { en: 'Long', zh: '龙' },
  'สูงเม่น': { en: 'Sung Men', zh: '颂门' },
  'เด่นชัย': { en: 'Den Chai', zh: '登猜' },
  'สอง': { en: 'Song', zh: '松' },
  'วังชิ้น': { en: 'Wang Chin', zh: '旺真' },
  'หนองม่วงไข่': { en: 'Nong Muang Khai', zh: '侬蒙开' },
  'เมืองพะเยา': { en: 'Mueang Phayao', zh: '帕尧' },
  'จุน': { en: 'Chun', zh: '准' },
  'เชียงคำ': { en: 'Chiang Kham', zh: '清甘' },
  'เชียงม่วน': { en: 'Chiang Muan', zh: '清满' },
  'ดอกคำใต้': { en: 'Dok Khamtai', zh: '铎甘泰' },
  'ปง': { en: 'Pong', zh: '蓬' },
  'แม่ใจ': { en: 'Mae Chai', zh: '湄猜' },
  'ภูซาง': { en: 'Phu Sang', zh: '普桑' },
  'ภูกามยาว': { en: 'Phu Kamyao', zh: '普甘尧' },
  'เมืองภูเก็ต': { en: 'Mueang Phuket', zh: '普吉' },
  'กะทู้': { en: 'Kathu', zh: '卡图' },
  'ถลาง': { en: 'Thalang', zh: '塔朗' },
  'เมืองมหาสารคาม': { en: 'Mueang Maha Sarakham', zh: '玛哈沙拉堪' },
  'แกดำ': { en: 'Kae Dam', zh: '皆丹' },
  'โกสุมพิสัย': { en: 'Kosum Phisai', zh: '哥松披赛' },
  'กันทรวิชัย': { en: 'Kantharawichai', zh: '甘他拉威猜' },
  'เชียงยืน': { en: 'Chiang Yuen', zh: '清元' },
  'บรบือ': { en: 'Borabue', zh: '波拉波' },
  'นาเชือก': { en: 'Na Chueak', zh: '那绰' },
  'พยัคฆภูมิพิสัย': { en: 'Phayakkhaphum Phisai', zh: '披耶卡蓬披赛' },
  'วาปีปทุม': { en: 'Wapi Pathum', zh: '瓦比巴吞' },
  'นาดูน': { en: 'Na Dun', zh: '那敦' },
  'ยางสีสุราช': { en: 'Yang Sisurat', zh: '洋是苏叻' },
  'กุดรัง': { en: 'Kut Rang', zh: '固朗' },
  'ชื่นชม': { en: 'Chuen Chom', zh: '春仲' },
  'เมืองมุกดาหาร': { en: 'Mueang Mukdahan', zh: '穆达汉' },
  'นิคมคำสร้อย': { en: 'Nikhom Kham Soi', zh: '尼空甘索' },
  'ดอนตาล': { en: 'Don Tan', zh: '敦丹' },
  'ดงหลวง': { en: 'Dong Luang', zh: '东銮' },
  'คำชะอี': { en: 'Khamcha-I', zh: '甘差伊' },
  'หว้านใหญ่': { en: 'Wan Yai', zh: '万艾' },
  'หนองสูง': { en: 'Nong Sung', zh: '侬颂' },
  'เมืองแม่ฮ่องสอน': { en: 'Mueang Mae Hong Son', zh: '夜丰颂' },
  'ขุนยวม': { en: 'Khun Yuam', zh: '昆元' },
  'ปาย': { en: 'Pai', zh: '派' },
  'แม่สะเรียง': { en: 'Mae Sariang', zh: '湄沙良' },
  'แม่ลาน้อย': { en: 'Mae La Noi', zh: '湄拉莲' },
  'สบเมย': { en: 'Sop Moei', zh: '索梅' },
  'ปางมะผ้า': { en: 'Pang Mapha', zh: '庞玛帕' },
  'เมืองยโสธร': { en: 'Mueang Yasothon', zh: '益梭通' },
  'ทรายมูล': { en: 'Sai Mun', zh: '赛满' },
  'กุดชุม': { en: 'Kut Chum', zh: '固春' },
  'คำเขื่อนแก้ว': { en: 'Kham Khuean Kaeo', zh: '甘昆缴' },
  'ป่าติ้ว': { en: 'Pa Tio', zh: '巴迪奥' },
  'มหาชนะชัย': { en: 'Maha Chana Chai', zh: '玛哈差那猜' },
  'ค้อวัง': { en: 'Kho Wang', zh: '阔旺' },
  'เลิงนกทา': { en: 'Loeng Nok Tha', zh: '楞诺塔' },
  'ไทยเจริญ': { en: 'Thai Charoen', zh: '泰乍能' },
  'เมืองยะลา': { en: 'Mueang Yala', zh: '也拉' },
  'เบตง': { en: 'Betong', zh: '勿洞' },
  'บันนังสตา': { en: 'Bannang Sata', zh: '班南沙塔' },
  'ธารโต': { en: 'Than To', zh: '探托' },
  'ยะหา': { en: 'Yaha', zh: '亚哈' },
  'รามัน': { en: 'Raman', zh: '拉曼' },
  'กาบัง': { en: 'Kabang', zh: '卡邦' },
  'กรงปินัง': { en: 'Krong Pinang', zh: '克隆比南' },
  'เมืองร้อยเอ็ด': { en: 'Mueang Roi Et', zh: '黎逸' },
  'เกษตรวิสัย': { en: 'Kaset Wisai', zh: '卡实威赛' },
  'ปทุมรัตต์': { en: 'Pathum Rat', zh: '巴吞叻' },
  'จตุรพักตรพิมาน': { en: 'Chaturaphak Phiman', zh: '乍杜拉帕披曼' },
  'ธวัชบุรี': { en: 'Thawat Buri', zh: '他瓦武里' },
  'พนมไพร': { en: 'Phanom Phrai', zh: '帕侬派' },
  'โพนทอง': { en: 'Phon Thong', zh: '蓬通' },
  'โพธิ์ชัย': { en: 'Pho Chai', zh: '菩猜' },
  'หนองพอก': { en: 'Nong Phok', zh: '侬蒲' },
  'เสลภูมิ': { en: 'Selaphum', zh: '塞拉蓬' },
  'สุวรรณภูมิ': { en: 'Suwannaphum', zh: '素万那普' },
  'เมืองสรวง': { en: 'Mueang Suang', zh: '孟素安' },
  'โพนทราย': { en: 'Phon Sai', zh: '蓬赛' },
  'อาจสามารถ': { en: 'At Samat', zh: '阿沙玛' },
  'เมยวดี': { en: 'Moei Wadi', zh: '梅瓦迪' },
  'ศรีสมเด็จ': { en: 'Si Somdet', zh: '是颂德' },
  'จังหาร': { en: 'Changhan', zh: '昌汉' },
  'เชียงขวัญ': { en: 'Chiang Khwan', zh: '清宽' },
  'หนองฮี': { en: 'Nong Hi', zh: '侬希' },
  'ทุ่งเขาหลวง': { en: 'Thung Khao Luang', zh: '通考銮' },
  'เมืองระนอง': { en: 'Mueang Ranong', zh: '拉廊' },
  'ละอุ่น': { en: 'La-Un', zh: '拉温' },
  'กะเปอร์': { en: 'Kapoe', zh: '卡坡' },
  'กระบุรี': { en: 'Kra Buri', zh: '格拉武里' },
  'สุขสำราญ': { en: 'Suk Samran', zh: '素沙兰' },
  'เมืองระยอง': { en: 'Mueang Rayong', zh: '罗勇' },
  'บ้านฉาง': { en: 'Ban Chang', zh: '班昌' },
  'แกลง': { en: 'Klaeng', zh: '格朗' },
  'วังจันทร์': { en: 'Wang Chan', zh: '旺占' },
  'บ้านค่าย': { en: 'Ban Khai', zh: '班开' },
  'ปลวกแดง': { en: 'Pluak Daeng', zh: '蒲阿铃' },
  'เขาชะเมา': { en: 'Khao Chamao', zh: '考差冒' },
  'นิคมพัฒนา': { en: 'Nikhom Phatthana', zh: '尼空帕他那' },
  'เมืองราชบุรี': { en: 'Mueang Ratchaburi', zh: '叻丕' },
  'จอมบึง': { en: 'Chom Bueng', zh: '仲汶' },
  'สวนผึ้ง': { en: 'Suan Phueng', zh: '素安蓬' },
  'ดำเนินสะดวก': { en: 'Damnoen Saduak', zh: '丹嫩沙端' },
  'บ้านโป่ง': { en: 'Ban Pong', zh: '班蓬' },
  'บางแพ': { en: 'Bang Phae', zh: '挽佩' },
  'โพธาราม': { en: 'Photharam', zh: '菩他兰' },
  'ปากท่อ': { en: 'Pak Tho', zh: '北陀' },
  'วัดเพลง': { en: 'Wat Phleng', zh: '越平' },
  'บ้านคา': { en: 'Ban Kha', zh: '班卡' },
  'เมืองลพบุรี': { en: 'Mueang Lop Buri', zh: '华富里' },
  'พัฒนานิคม': { en: 'Phatthana Nikhom', zh: '帕他那尼空' },
  'โคกสำโรง': { en: 'Khok Samrong', zh: '廓三榕' },
  'ชัยบาดาล': { en: 'Chai Badan', zh: '猜巴丹' },
  'ท่าวุ้ง': { en: 'Tha Wung', zh: '塔翁' },
  'บ้านหมี่': { en: 'Ban Mi', zh: '班米' },
  'ท่าหลวง': { en: 'Tha Luang', zh: '塔銮' },
  'สระโบสถ์': { en: 'Sa Bot', zh: '沙博' },
  'โคกเจริญ': { en: 'Khok Charoen', zh: '廓乍能' },
  'ลำสนธิ': { en: 'Lam Sonthi', zh: '蓝颂提' },
  'หนองม่วง': { en: 'Nong Muang', zh: '侬蒙' },
  'เมืองลำปาง': { en: 'Mueang Lampang', zh: '南邦' },
  'แม่เมาะ': { en: 'Mae Mo', zh: '湄莫' },
  'เกาะคา': { en: 'Ko Kha', zh: '高卡' },
  'เสริมงาม': { en: 'Soem Ngam', zh: '森雅姆' },
  'งาว': { en: 'Ngao', zh: '敖' },
  'แจ้ห่ม': { en: 'Chae Hom', zh: '采弘' },
  'วังเหนือ': { en: 'Wang Nuea', zh: '旺嫩' },
  'เถิน': { en: 'Thoen', zh: '吞' },
  'แม่พริก': { en: 'Mae Phrik', zh: '湄帕里' },
  'แม่ทะ': { en: 'Mae Tha', zh: '湄塔' },
  'สบปราบ': { en: 'Sop Prap', zh: '索巴拉' },
  'ห้างฉัตร': { en: 'Hang Chat', zh: '昂差' },
  'เมืองปาน': { en: 'Mueang Pan', zh: '孟潘' },
  'เมืองลำพูน': { en: 'Mueang Lamphun', zh: '南奔' },
  'แม่ทา': { en: 'Mae Tha', zh: '湄塔' },
  'บ้านโฮ่ง': { en: 'Ban Hong', zh: '班洪' },
  'ลี้': { en: 'Li', zh: '里' },
  'ทุ่งหัวช้าง': { en: 'Thung Hua Chang', zh: '通华昌' },
  'ป่าซาง': { en: 'Pa Sang', zh: '巴桑' },
  'บ้านธิ': { en: 'Ban Thi', zh: '班提' },
  'เวียงหนองล่อง': { en: 'Wiang Nong Long', zh: '威昂侬龙' },
  'เมืองเลย': { en: 'Mueang Loei', zh: '黎府' },
  'นาด้วง': { en: 'Na Duang', zh: '那端' },
  'เชียงคาน': { en: 'Chiang Khan', zh: '清坎' },
  'ปากชม': { en: 'Pak Chom', zh: '北仲' },
  'ด่านซ้าย': { en: 'Dan Sai', zh: '丹赛' },
  'นาแห้ว': { en: 'Na Haeo', zh: '那号' },
  'ภูเรือ': { en: 'Phu Ruea', zh: '普勒阿' },
  'ท่าลี่': { en: 'Tha Li', zh: '塔里' },
  'วังสะพุง': { en: 'Wang Saphung', zh: '旺沙蓬' },
  'ภูกระดึง': { en: 'Phu Kradueng', zh: '普格拉登' },
  'ภูหลวง': { en: 'Phu Luang', zh: '普銮' },
  'ผาขาว': { en: 'Pha Khao', zh: '帕考' },
  'เอราวัณ': { en: 'Erawan', zh: '埃拉万' },
  'หนองหิน': { en: 'Nong Hin', zh: '侬欣' },
  'เมืองศรีสะเกษ': { en: 'Mueang Si Sa Ket', zh: '四色菊' },
  'ยางชุมน้อย': { en: 'Yang Chum Noi', zh: '洋春莲' },
  'กันทรารมย์': { en: 'Kanthararom', zh: '甘他拉隆' },
  'กันทรลักษ์': { en: 'Kantharalak', zh: '甘他拉叻' },
  'ขุขันธ์': { en: 'Khukhan', zh: '库堪' },
  'ไพรบึง': { en: 'Phrai Bueng', zh: '派汶' },
  'ปรางค์กู่': { en: 'Prang Ku', zh: '庞固' },
  'ขุนหาญ': { en: 'Khun Han', zh: '昆汉' },
  'ราษีไศล': { en: 'Rasi Salai', zh: '拉西沙莱' },
  'อุทุมพรพิสัย': { en: 'Uthumphon Phisai', zh: '乌吞蓬披赛' },
  'บึงบูรพ์': { en: 'Bueng Bun', zh: '汶汶' },
  'ห้วยทับทัน': { en: 'Huai Thap Than', zh: '会塔探' },
  'โนนคูณ': { en: 'Non Khun', zh: '侬昆' },
  'ศรีรัตนะ': { en: 'Si Rattana', zh: '是叻他那' },
  'น้ำเกลี้ยง': { en: 'Nam Kliang', zh: '南格良' },
  'วังหิน': { en: 'Wang Hin', zh: '旺欣' },
  'ภูสิงห์': { en: 'Phu Sing', zh: '普信' },
  'เมืองจันทร์': { en: 'Mueang Chan', zh: '孟占' },
  'เบญจลักษ์': { en: 'Benchalak', zh: '奔乍拉' },
  'พยุห์': { en: 'Phayu', zh: '帕育' },
  'โพธิ์ศรีสุวรรณ': { en: 'Pho Si Suwan', zh: '菩是素万' },
  'ศิลาลาด': { en: 'Sila Lat', zh: '是拉叻' },
  'เมืองสกลนคร': { en: 'Mueang Sakon Nakhon', zh: '色军' },
  'กุสุมาลย์': { en: 'Kusuman', zh: '固素曼' },
  'กุดบาก': { en: 'Kut Bak', zh: '固巴' },
  'พรรณานิคม': { en: 'Phanna Nikhom', zh: '潘那尼空' },
  'พังโคน': { en: 'Phang Khon', zh: '庞孔' },
  'วาริชภูมิ': { en: 'Waritchaphum', zh: '瓦里差蓬' },
  'นิคมน้ำอูน': { en: 'Nikhom Nam Un', zh: '尼空南温' },
  'วานรนิวาส': { en: 'Wanon Niwat', zh: '瓦农尼瓦' },
  'คำตากล้า': { en: 'Kham Ta Kla', zh: '甘塔克拉' },
  'บ้านม่วง': { en: 'Ban Muang', zh: '班蒙' },
  'อากาศอำนวย': { en: 'Akat Amnuai', zh: '阿甲安内' },
  'สว่างแดนดิน': { en: 'Sawang Daen Din', zh: '沙旺甸丁' },
  'ส่องดาว': { en: 'Song Dao', zh: '松道' },
  'เต่างอย': { en: 'Tao Ngoi', zh: '岛阿' },
  'โคกศรีสุพรรณ': { en: 'Khok Si Suphan', zh: '廓是素攀' },
  'เจริญศิลป์': { en: 'Charoen Sin', zh: '乍能信' },
  'โพนนาแก้ว': { en: 'Phon Na Kaeo', zh: '蓬那缴' },
  'ภูพาน': { en: 'Phu Phan', zh: '普潘' },
  'เมืองสงขลา': { en: 'Mueang Songkhla', zh: '宋卡' },
  'สทิงพระ': { en: 'Sathing Phra', zh: '沙廷拍' },
  'จะนะ': { en: 'Chana', zh: '差那' },
  'นาทวี': { en: 'Na Thawi', zh: '那他威' },
  'เทพา': { en: 'Thepha', zh: '贴帕' },
  'สะบ้าย้อย': { en: 'Saba Yoi', zh: '沙巴育' },
  'ระโนด': { en: 'Ranot', zh: '拉诺' },
  'กระแสสินธุ์': { en: 'Krasae Sin', zh: '格拉塞信' },
  'รัตภูมิ': { en: 'Rattaphum', zh: '叻他蓬' },
  'สะเดา': { en: 'Sadao', zh: '沙岛' },
  'หาดใหญ่': { en: 'Hat Yai', zh: '哈艾' },
  'นาหม่อม': { en: 'Na Mom', zh: '那姆' },
  'ควนเนียง': { en: 'Khuan Niang', zh: '昆年' },
  'บางกล่ำ': { en: 'Bang Klam', zh: '挽甘' },
  'สิงหนคร': { en: 'Singhanakhon', zh: '信哈那空' },
  'คลองหอยโข่ง': { en: 'Khlong Hoi Khong', zh: '空海孔' },
  'เมืองสตูล': { en: 'Mueang Satun', zh: '沙敦' },
  'ควนโดน': { en: 'Khuan Don', zh: '昆敦' },
  'ควนกาหลง': { en: 'Khuan Kalong', zh: '昆卡隆' },
  'ท่าแพ': { en: 'Tha Phae', zh: '塔佩' },
  'ละงู': { en: 'La-Ngu', zh: '拉阿' },
  'ทุ่งหว้า': { en: 'Thung Wa', zh: '通瓦' },
  'มะนัง': { en: 'Manang', zh: '玛南' },
  'เมืองสมุทรปราการ': { en: 'Mueang Samut Prakan', zh: '北榄' },
  'บางบ่อ': { en: 'Bang Bo', zh: '挽波' },
  'บางพลี': { en: 'Bang Phli', zh: '挽普里' },
  'พระประแดง': { en: 'Phra Pradaeng', zh: '拍巴登' },
  'พระสมุทรเจดีย์': { en: 'Phra Samut Chedi', zh: '拍沙没节迪' },
  'บางเสาธง': { en: 'Bang Sao Thong', zh: '挽绍通' },
  'เมืองสมุทรสงคราม': { en: 'Mueang Samut Songkhram', zh: '夜功' },
  'บางคนที': { en: 'Bang Khonthi', zh: '挽孔提' },
  'อัมพวา': { en: 'Amphawa', zh: '安帕瓦' },
  'เมืองสมุทรสาคร': { en: 'Mueang Samut Sakhon', zh: '龙仔厝' },
  'กระทุ่มแบน': { en: 'Krathum Baen', zh: '格拉通边' },
  'บ้านแพ้ว': { en: 'Ban Phaeo', zh: '班佩' },
  'เมืองสระแก้ว': { en: 'Mueang Sa Kaeo', zh: '沙缴' },
  'คลองหาด': { en: 'Khlong Hat', zh: '空哈' },
  'ตาพระยา': { en: 'Ta Phraya', zh: '塔披耶' },
  'วังน้ำเย็น': { en: 'Wang Nam Yen', zh: '旺南演' },
  'วัฒนานคร': { en: 'Watthana Nakhon', zh: '哇他那那空' },
  'อรัญประเทศ': { en: 'Aranyaprathet', zh: '阿兰亚巴帖' },
  'เขาฉกรรจ์': { en: 'Khao Chakan', zh: '考乍甘' },
  'โคกสูง': { en: 'Khok Sung', zh: '廓颂' },
  'วังสมบูรณ์': { en: 'Wang Sombun', zh: '旺颂汶' },
  'เมืองสระบุรี': { en: 'Mueang Saraburi', zh: '北标' },
  'แก่งคอย': { en: 'Kaeng Khoi', zh: '坑阔' },
  'หนองแค': { en: 'Nong Khae', zh: '侬坑' },
  'วิหารแดง': { en: 'Wihan Daeng', zh: '威汉铃' },
  'หนองแซง': { en: 'Nong Saeng', zh: '侬盛' },
  'บ้านหมอ': { en: 'Ban Mo', zh: '班莫' },
  'ดอนพุด': { en: 'Don Phut', zh: '敦普' },
  'หนองโดน': { en: 'Nong Don', zh: '侬敦' },
  'พระพุทธบาท': { en: 'Phra Phutthabat', zh: '拍普他巴' },
  'เสาไห้': { en: 'Sao Hai', zh: '绍海' },
  'มวกเหล็ก': { en: 'Muak Lek', zh: '莫勒' },
  'วังม่วง': { en: 'Wang Muang', zh: '旺蒙' },
  'เมืองสิงห์บุรี': { en: 'Mueang Sing Buri', zh: '信武里' },
  'บางระจัน': { en: 'Bang Rachan', zh: '挽拉占' },
  'ค่ายบางระจัน': { en: 'Khai Bang Rachan', zh: '开挽拉占' },
  'พรหมบุรี': { en: 'Phrom Buri', zh: '拍隆武里' },
  'ท่าช้าง': { en: 'Tha Chang', zh: '塔昌' },
  'อินทร์บุรี': { en: 'In Buri', zh: '因武里' },
  'เมืองสุโขทัย': { en: 'Mueang Sukhothai', zh: '素可泰' },
  'บ้านด่านลานหอย': { en: 'Ban Dan Lan Hoi', zh: '班丹兰海' },
  'คีรีมาศ': { en: 'Khiri Mat', zh: '基里玛' },
  'กงไกรลาศ': { en: 'Kong Krailat', zh: '公格莱叻' },
  'ศรีสัชนาลัย': { en: 'Si Satchanalai', zh: '是沙差那莱' },
  'ศรีสำโรง': { en: 'Si Samrong', zh: '是三榕' },
  'สวรรคโลก': { en: 'Sawankhalok', zh: '沙旺卡洛' },
  'ศรีนคร': { en: 'Si Nakhon', zh: '是那空' },
  'ทุ่งเสลี่ยม': { en: 'Thung Saliam', zh: '通沙良' },
  'เมืองสุพรรณบุรี': { en: 'Mueang Suphan Buri', zh: '素攀武里' },
  'เดิมบางนางบวช': { en: 'Doem Bang Nang Buat', zh: '敦挽南蒲阿' },
  'ด่านช้าง': { en: 'Dan Chang', zh: '丹昌' },
  'บางปลาม้า': { en: 'Bang Pla Ma', zh: '挽巴拉玛' },
  'ศรีประจันต์': { en: 'Si Prachan', zh: '是巴占' },
  'ดอนเจดีย์': { en: 'Don Chedi', zh: '敦节迪' },
  'สองพี่น้อง': { en: 'Song Phi Nong', zh: '松披侬' },
  'สามชุก': { en: 'Sam Chuk', zh: '三出' },
  'อู่ทอง': { en: 'U Thong', zh: '乌通' },
  'หนองหญ้าไซ': { en: 'Nong Ya Sai', zh: '侬亚赛' },
  'เมืองสุราษฎร์ธานี': { en: 'Mueang Surat Thani', zh: '素叻他尼' },
  'กาญจนดิษฐ์': { en: 'Kanchanadit', zh: '甘乍那迪' },
  'ดอนสัก': { en: 'Don Sak', zh: '敦沙' },
  'เกาะสมุย': { en: 'Ko Samui', zh: '高苏梅' },
  'เกาะพะงัน': { en: 'Ko Pha-Ngan', zh: '高帕雅' },
  'ไชยา': { en: 'Chaiya', zh: '猜耶' },
  'ท่าชนะ': { en: 'Tha Chana', zh: '塔差那' },
  'คีรีรัฐนิคม': { en: 'Khiri Rat Nikhom', zh: '基里叻尼空' },
  'บ้านตาขุน': { en: 'Ban Ta Khun', zh: '班塔昆' },
  'พนม': { en: 'Phanom', zh: '帕侬' },
  'ท่าฉาง': { en: 'Tha Chang', zh: '塔昌' },
  'บ้านนาสาร': { en: 'Ban Na San', zh: '班那讪' },
  'บ้านนาเดิม': { en: 'Ban Na Doem', zh: '班那敦' },
  'เคียนซา': { en: 'Khian Sa', zh: '建沙' },
  'เวียงสระ': { en: 'Wiang Sa', zh: '威昂沙' },
  'พระแสง': { en: 'Phrasaeng', zh: '帕盛' },
  'พุนพิน': { en: 'Phunphin', zh: '普宾' },
  'ชัยบุรี': { en: 'Chai Buri', zh: '猜武里' },
  'วิภาวดี': { en: 'Wiphawadi', zh: '威帕瓦迪' },
  'เมืองสุรินทร์': { en: 'Mueang Surin', zh: '素林' },
  'ชุมพลบุรี': { en: 'Chumphon Buri', zh: '春蓬武里' },
  'ท่าตูม': { en: 'Tha Tum', zh: '塔吞' },
  'จอมพระ': { en: 'Chom Phra', zh: '仲拍' },
  'ปราสาท': { en: 'Prasat', zh: '巴萨' },
  'กาบเชิง': { en: 'Kap Choeng', zh: '甲冲' },
  'รัตนบุรี': { en: 'Rattanaburi', zh: '叻他那武里' },
  'สนม': { en: 'Sanom', zh: '沙侬' },
  'ศีขรภูมิ': { en: 'Sikhoraphum', zh: '是廓拉蓬' },
  'สังขะ': { en: 'Sangkha', zh: '桑卡' },
  'ลำดวน': { en: 'Lamduan', zh: '蓝端' },
  'สำโรงทาบ': { en: 'Samrong Thap', zh: '三榕塔' },
  'บัวเชด': { en: 'Buachet', zh: '蒲切' },
  'พนมดงรัก': { en: 'Phanom Dong Rak', zh: '帕侬东乐' },
  'ศรีณรงค์': { en: 'Si Narong', zh: '是那隆' },
  'เขวาสินรินทร์': { en: 'Khwao Sinarin', zh: '快是那林' },
  'โนนนารายณ์': { en: 'Non Narai', zh: '侬那莱' },
  'เมืองหนองคาย': { en: 'Mueang Nong Khai', zh: '廊开' },
  'ท่าบ่อ': { en: 'Tha Bo', zh: '塔波' },
  'โพนพิสัย': { en: 'Phon Phisai', zh: '蓬披赛' },
  'ศรีเชียงใหม่': { en: 'Si Chiang Mai', zh: '是清迈' },
  'สังคม': { en: 'Sangkhom', zh: '桑孔' },
  'สระใคร': { en: 'Sakhrai', zh: '沙莱' },
  'เฝ้าไร่': { en: 'Fao Rai', zh: '佛莱' },
  'รัตนวาปี': { en: 'Rattanawapi', zh: '叻他那瓦比' },
  'โพธิ์ตาก': { en: 'Pho Tak', zh: '菩达' },
  'เมืองหนองบัวลำภู': { en: 'Mueang Nong Bua Lam Phu', zh: '侬蒲蓝普' },
  'นากลาง': { en: 'Na Klang', zh: '那格朗' },
  'โนนสัง': { en: 'Non Sang', zh: '侬桑' },
  'ศรีบุญเรือง': { en: 'Si Bun Rueang', zh: '是汶勒昂' },
  'สุวรรณคูหา': { en: 'Suwannakhuha', zh: '素万古哈' },
  'นาวัง': { en: 'Na Wang', zh: '那旺' },
  'เมืองอ่างทอง': { en: 'Mueang Ang Thong', zh: '红统' },
  'ไชโย': { en: 'Chaiyo', zh: '猜育' },
  'ป่าโมก': { en: 'Pa Mok', zh: '巴莫' },
  'โพธิ์ทอง': { en: 'Pho Thong', zh: '菩通' },
  'แสวงหา': { en: 'Sawaeng Ha', zh: '沙盛哈' },
  'วิเศษชัยชาญ': { en: 'Wiset Chai Chan', zh: '威实猜占' },
  'สามโก้': { en: 'Samko', zh: '三高' },
  'เมืองอำนาจเจริญ': { en: 'Mueang Amnat Charoen', zh: '安纳乍能' },
  'ชานุมาน': { en: 'Chanuman', zh: '差努曼' },
  'ปทุมราชวงศา': { en: 'Pathum Ratchawongsa', zh: '巴吞拉差旺萨' },
  'พนา': { en: 'Phana', zh: '帕那' },
  'เสนางคนิคม': { en: 'Senangkhanikhom', zh: '社南卡尼空' },
  'หัวตะพาน': { en: 'Hua Taphan', zh: '华塔潘' },
  'ลืออำนาจ': { en: 'Lue Amnat', zh: '勒安纳' },
  'เมืองอุดรธานี': { en: 'Mueang Udon Thani', zh: '乌隆他尼' },
  'กุดจับ': { en: 'Kut Chap', zh: '固乍' },
  'หนองวัวซอ': { en: 'Nong Wua So', zh: '侬瓦索' },
  'กุมภวาปี': { en: 'Kumphawapi', zh: '甘帕瓦比' },
  'โนนสะอาด': { en: 'Non Sa-At', zh: '侬沙阿' },
  'หนองหาน': { en: 'Nong Han', zh: '侬汉' },
  'ทุ่งฝน': { en: 'Thung Fon', zh: '通丰' },
  'ไชยวาน': { en: 'Chai Wan', zh: '猜万' },
  'ศรีธาตุ': { en: 'Si That', zh: '是塔' },
  'วังสามหมอ': { en: 'Wang Sam Mo', zh: '旺三莫' },
  'บ้านดุง': { en: 'Ban Dung', zh: '班东' },
  'บ้านผือ': { en: 'Ban Phue', zh: '班普' },
  'น้ำโสม': { en: 'Nam Som', zh: '南颂' },
  'เพ็ญ': { en: 'Phen', zh: '编' },
  'สร้างคอม': { en: 'Sang Khom', zh: '桑孔' },
  'หนองแสง': { en: 'Nong Saeng', zh: '侬盛' },
  'นายูง': { en: 'Na Yung', zh: '那荣' },
  'พิบูลย์รักษ์': { en: 'Phibun Rak', zh: '披汶乐' },
  'กู่แก้ว': { en: 'Ku Kaeo', zh: '固缴' },
  'ประจักษ์ศิลปาคม': { en: 'Prachaksinlapakhom', zh: '巴乍信拉巴孔' },
  'เมืองอุทัยธานี': { en: 'Mueang Uthai Thani', zh: '乌泰他尼' },
  'ทัพทัน': { en: 'Thap Than', zh: '塔探' },
  'สว่างอารมณ์': { en: 'Sawang Arom', zh: '沙旺阿隆' },
  'หนองฉาง': { en: 'Nong Chang', zh: '侬昌' },
  'หนองขาหย่าง': { en: 'Nong Khayang', zh: '侬卡阳' },
  'บ้านไร่': { en: 'Ban Rai', zh: '班莱' },
  'ลานสัก': { en: 'Lan Sak', zh: '兰沙' },
  'ห้วยคต': { en: 'Huai Khot', zh: '会阔' },
  'เมืองอุตรดิตถ์': { en: 'Mueang Uttaradit', zh: '程逸' },
  'ตรอน': { en: 'Tron', zh: '特隆' },
  'ท่าปลา': { en: 'Tha Pla', zh: '塔巴拉' },
  'น้ำปาด': { en: 'Nam Pat', zh: '南巴' },
  'ฟากท่า': { en: 'Fak Tha', zh: '法塔' },
  'บ้านโคก': { en: 'Ban Khok', zh: '班廓' },
  'พิชัย': { en: 'Phichai', zh: '披猜' },
  'ลับแล': { en: 'Laplae', zh: '拉普莱' },
  'ทองแสนขัน': { en: 'Thong Saen Khan', zh: '通森坎' },
  'เมืองอุบลราชธานี': { en: 'Mueang Ubon Ratchathani', zh: '乌汶' },
  'ศรีเมืองใหม่': { en: 'Si Mueang Mai', zh: '是孟迈' },
  'โขงเจียม': { en: 'Khong Chiam', zh: '孔建' },
  'เขื่องใน': { en: 'Khueang Nai', zh: '昆奈' },
  'เขมราฐ': { en: 'Khemarat', zh: '克玛叻' },
  'เดชอุดม': { en: 'Det Udom', zh: '德乌东' },
  'นาจะหลวย': { en: 'Na Chaluai', zh: '那差莱' },
  'น้ำยืน': { en: 'Nam Yuen', zh: '南元' },
  'บุณฑริก': { en: 'Buntharik', zh: '汶塔里' },
  'ตระการพืชผล': { en: 'Trakan Phuet Phon', zh: '达堪普蓬' },
  'กุดข้าวปุ้น': { en: 'Kut Khaopun', zh: '固考奔' },
  'ม่วงสามสิบ': { en: 'Muang Sam Sip', zh: '蒙三实' },
  'วารินชำราบ': { en: 'Warin Chamrap', zh: '瓦林差拉' },
  'พิบูลมังสาหาร': { en: 'Phibun Mangsahan', zh: '披汶曼沙汉' },
  'ตาลสุม': { en: 'Tan Sum', zh: '丹颂' },
  'โพธิ์ไทร': { en: 'Pho Sai', zh: '菩赛' },
  'สำโรง': { en: 'Samrong', zh: '三榕' },
  'ดอนมดแดง': { en: 'Don Mot Daeng', zh: '敦摩铃' },
  'สิรินธร': { en: 'Sirindhorn', zh: '诗琳通' },
  'ทุ่งศรีอุดม': { en: 'Thung Si Udom', zh: '通是乌东' },
  'นาเยีย': { en: 'Na Yia', zh: '那耶' },
  'นาตาล': { en: 'Na Tan', zh: '那丹' },
  'เหล่าเสือโก้ก': { en: 'Lao Suea Kok', zh: '劳舍廓' },
  'สว่างวีระวงศ์': { en: 'Sawang Wirawong', zh: '沙旺威拉旺' },
  'น้ำขุ่น': { en: 'Nam Khun', zh: '南昆' },
}
