export const PROVINCE_I18N: Record<string, { en: string; zh: string }> = {
  กรุงเทพมหานคร: { en: 'Bangkok', zh: '曼谷' },
  กระบี่: { en: 'Krabi', zh: '甲米' },
  กาญจนบุรี: { en: 'Kanchanaburi', zh: '北碧' },
  กาฬสินธุ์: { en: 'Kalasin', zh: '加拉信' },
  กำแพงเพชร: { en: 'Kamphaeng Phet', zh: '甘烹碧' },
  ขอนแก่น: { en: 'Khon Kaen', zh: '孔敬' },
  จันทบุรี: { en: 'Chanthaburi', zh: '尖竹汶' },
  ฉะเชิงเทรา: { en: 'Chachoengsao', zh: '北柳' },
  ชลบุรี: { en: 'Chonburi', zh: '春武里' },
  ชัยนาท: { en: 'Chai Nat', zh: '猜纳' },
  ชัยภูมิ: { en: 'Chaiyaphum', zh: '猜也奔' },
  ชุมพร: { en: 'Chumphon', zh: '春蓬' },
  เชียงราย: { en: 'Chiang Rai', zh: '清莱' },
  เชียงใหม่: { en: 'Chiang Mai', zh: '清迈' },
  ตรัง: { en: 'Trang', zh: '董里' },
  ตราด: { en: 'Trat', zh: '达叻' },
  ตาก: { en: 'Tak', zh: '来兴' },
  นครนายก: { en: 'Nakhon Nayok', zh: '那空那育' },
  นครปฐม: { en: 'Nakhon Pathom', zh: '佛统' },
  นครพนม: { en: 'Nakhon Phanom', zh: '那空拍侬' },
  นครราชสีมา: { en: 'Nakhon Ratchasima', zh: '呵叻' },
  นครศรีธรรมราช: { en: 'Nakhon Si Thammarat', zh: '洛坤' },
  นครสวรรค์: { en: 'Nakhon Sawan', zh: '那空沙旺' },
  นนทบุรี: { en: 'Nonthaburi', zh: '暖武里' },
  นราธิวาส: { en: 'Narathiwat', zh: '那拉提瓦' },
  น่าน: { en: 'Nan', zh: '楠' },
  บึงกาฬ: { en: 'Bueng Kan', zh: '汶干' },
  บุรีรัมย์: { en: 'Buriram', zh: '武里南' },
  ปทุมธานี: { en: 'Pathum Thani', zh: '巴吞他尼' },
  ประจวบคีรีขันธ์: { en: 'Prachuap Khiri Khan', zh: '巴蜀' },
  ปราจีนบุรี: { en: 'Prachinburi', zh: '巴真' },
  ปัตตานี: { en: 'Pattani', zh: '北大年' },
  พระนครศรีอยุธยา: { en: 'Phra Nakhon Si Ayutthaya', zh: '大城' },
  พังงา: { en: 'Phang Nga', zh: '攀牙' },
  พัทลุง: { en: 'Phatthalung', zh: '博他仑' },
  พิจิตร: { en: 'Phichit', zh: '披集' },
  พิษณุโลก: { en: 'Phitsanulok', zh: '彭世洛' },
  เพชรบุรี: { en: 'Phetchaburi', zh: '佛丕' },
  เพชรบูรณ์: { en: 'Phetchabun', zh: '碧差汶' },
  แพร่: { en: 'Phrae', zh: '帕' },
  พะเยา: { en: 'Phayao', zh: '帕尧' },
  ภูเก็ต: { en: 'Phuket', zh: '普吉' },
  มหาสารคาม: { en: 'Maha Sarakham', zh: '玛哈沙拉堪' },
  มุกดาหาร: { en: 'Mukdahan', zh: '莫达汉' },
  แม่ฮ่องสอน: { en: 'Mae Hong Son', zh: '夜丰颂' },
  ยโสธร: { en: 'Yasothon', zh: '益梭通' },
  ยะลา: { en: 'Yala', zh: '惹拉' },
  ร้อยเอ็ด: { en: 'Roi Et', zh: '黎逸' },
  ระนอง: { en: 'Ranong', zh: '拉廊' },
  ระยอง: { en: 'Rayong', zh: '罗勇' },
  ราชบุรี: { en: 'Ratchaburi', zh: '叻丕' },
  ลพบุรี: { en: 'Lopburi', zh: '华富里' },
  ลำปาง: { en: 'Lampang', zh: '南邦' },
  ลำพูน: { en: 'Lamphun', zh: '南奔' },
  เลย: { en: 'Loei', zh: '黎' },
  ศรีสะเกษ: { en: 'Sisaket', zh: '四色菊' },
  สกลนคร: { en: 'Sakon Nakhon', zh: '沙功那空' },
  สงขลา: { en: 'Songkhla', zh: '宋卡' },
  สตูล: { en: 'Satun', zh: '沙敦' },
  สมุทรปราการ: { en: 'Samut Prakan', zh: '北榄' },
  สมุทรสงคราม: { en: 'Samut Songkhram', zh: '夜功' },
  สมุทรสาคร: { en: 'Samut Sakhon', zh: '龙仔厝' },
  สระแก้ว: { en: 'Sa Kaeo', zh: '沙缴' },
  สระบุรี: { en: 'Saraburi', zh: '北标' },
  สิงห์บุรี: { en: 'Sing Buri', zh: '信武里' },
  สุโขทัย: { en: 'Sukhothai', zh: '素可泰' },
  สุพรรณบุรี: { en: 'Suphan Buri', zh: '素攀武里' },
  สุราษฎร์ธานี: { en: 'Surat Thani', zh: '素叻他尼' },
  สุรินทร์: { en: 'Surin', zh: '素林' },
  หนองคาย: { en: 'Nong Khai', zh: '廊开' },
  หนองบัวลำภู: { en: 'Nong Bua Lamphu', zh: '农磨兰普' },
  อ่างทอง: { en: 'Ang Thong', zh: '红统' },
  อำนาจเจริญ: { en: 'Amnat Charoen', zh: '安纳乍伦' },
  อุดรธานี: { en: 'Udon Thani', zh: '乌隆' },
  อุทัยธานี: { en: 'Uthai Thani', zh: '乌泰他尼' },
  อุตรดิตถ์: { en: 'Uttaradit', zh: '程逸' },
  อุบลราชธานี: { en: 'Ubon Ratchathani', zh: '乌汶' },
}
